### ISSUE TITLE
게시글 작성, 조회

### ISSUE THREAD

**Issue by abcshc** [No-Break/personal-posts#1]
각자 원하는 게시판을 spring, kotlin, jpa, mysql을 사용하여 개발합니다.

### 이번 목표는 게시글 작성, 조회입니다.

개인 별로 패키지, URL PATH prefix를 만들어서 개발을 진행합니다.
study.nobreak.personalposts.개인식별이름
ex) study.nobreak.personalposts.abcshc

궁금한 내용이나 정해지는 내용은 아래 코멘트로 작성해서 기록으로 남깁니다.

__이슈를 확인했다면 간단한 인사 코멘트를 추가해주시고 아래 체크박스에 체크해 주세요.__
- [x] abcshc
- [x] OseongminO
- [x] choiwonho
- [x] starr9622

**Comment by abcshc** [comment]
재미있게 해봅시다~

**Comment by OseongminO** [comment]
네~

**Comment by choiwonho** [comment]
네 확인했습니다~

**Comment by choiwonho** [comment]
> 재미있게 해봅시다~

코틀린 열심히 해야겠네요~

**Comment by choiwonho** [comment]
assign 다시 부탁 드립니다...

**Comment by starr9622** [comment]
> 재미있게 해봅시다~
 
ㅖ

**Comment by abcshc** [comment]
### 로컬 데이터베이스 설정을 위한 쿼리
```sql
CREATE USER 'nobreak'@'localhost' IDENTIFIED BY '1234';

CREATE DATABASE posts;

GRANT ALL PRIVILEGES ON posts.* TO 'nobreak'@'localhost';
```

비밀번호가 no 인 경우 spring.datasource.password 에서 잘못 전달하는 듯 합니다.
비밀번호를 no 로 하려다 삽질 했습니다.

테이블은 각자 2글자씩 prefix로 붙여 주세요. 안겹치게 아래에 작성해주세요.

- [x] abcshc: `so_`
- [x] OseongminO:
- [x] choiwonho: `wo_`
- [ ] starr9622:
