### ISSUE TITLE
notice board 프로젝트 기능목록

### ISSUE THREAD

**Issue by OseongminO** [No-Break/personal-posts#28]
**게시판 기능**
- 게시판 제목
- 게시판 내용
- 작성자 (로그인 기능 X)
- 작성일

**화면 기능**
- 목록 조회
- 상세 조회
- 등록, 수정
- 화면 페이징

- [x] abcshc
- [x] OseongminO
- [x] choiwonho
- [x] starr9622

**Comment by abcshc** [comment]
Page interface를 활용하여 개발을 진행할 예정입니다. 인터페이스의 구체적인 내용은 코멘트로 남겨 놓겠습니다.

**Comment by abcshc** [comment]
`org.springframework.data.domain.Page`, `org.springframework.data.domain.Pageable` 을 사용하여 개발하기를 권장합니다.
https://github.com/No-Break/personal-posts/pull/30 PR 내용을 참고하세요.
